[package]
name = "test_fixtures"
version = "0.1.0"
authors = ["jaxx"]
workspace = ".."
edition = "2018"

[lib]
name = "fixtures"
path = "src/lib.rs"

[dependencies]
test-crate2 = { path = "../test-crate2"}
